### ISSUE TITLE
Visual Studio 2017 Build

### ISSUE THREAD

**Issue by maxitimes** [openskipper/OpenSkipper#1]
Builds fine in VS2017
Most items work, processes log files and samples provided.

Couldn't get web server going by turning on ports - "Bad Request"
Couldn't get Display or view data on gagues - "Errors have occured: System.Collections.ArrayList"

Otherwise it worked well  

Anything help would be appreciated.

**Comment by melucas** [comment]
Hello,

Yes, that is not 100% documented anywhere yet.

**To get the web pages working:**
	- The www folder needs to be in the same folder as the OpenSkipper.exe
	- Change the default port number to something like 8080 on the File -> Settings page
	- Enable the web server.  Note, if Local Host Only is checked, you need to use http://localhost:8080 to access the pages

**Comment by melucas** [comment]
FYI.  You don't need to change the default port if you do not have any other web server installed and running on port 80.

**Comment by melucas** [comment]
**To get the xml forms to open:**
- Copy the xml file from OpenSkipperApplication\SampleDefinitions into the same folder as  the OpenSkipper.exe

**Comment by maxitimes** [comment]
Thank you
